"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Loader2, Sparkles, Wand2 } from "lucide-react";

import { generateContractFromDescription } from "@/ai/flows/generate-contract-from-description";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";

const formSchema = z.object({
  description: z.string().min(20, {
    message: "Please provide a more detailed description (at least 20 characters).",
  }),
});

export default function GenerateContractPage() {
  const [generatedContract, setGeneratedContract] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      description: "",
    },
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);
    setGeneratedContract("");
    try {
      const result = await generateContractFromDescription(values);
      if (result.contract) {
        setGeneratedContract(result.contract);
      } else {
        throw new Error("Failed to generate contract.");
      }
    } catch (error) {
      console.error(error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "There was a problem generating your contract. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="grid gap-8">
      <div>
        <h1 className="font-headline text-3xl font-bold">Contract Generator</h1>
        <p className="text-muted-foreground">
          Describe the contract you need, and our AI will draft a version for you.
        </p>
      </div>

      <Card>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)}>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Wand2 className="text-accent"/>
                Contract Description
              </CardTitle>
              <CardDescription>
                Be as specific as possible. Include parties, services, payment terms, and duration.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <FormField
                control={form.control}
                name="description"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <Textarea
                        placeholder="e.g., 'A freelance contract for a 3-month web development project with Acme Corp. Total project cost is $10,000, paid in two installments...'"
                        className="min-h-[150px] text-base"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </CardContent>
            <CardFooter>
              <Button type="submit" disabled={isLoading} size="lg">
                {isLoading ? (
                  <Loader2 className="animate-spin" />
                ) : (
                  <Sparkles className="mr-2 h-4 w-4" />
                )}
                Generate Contract
              </Button>
            </CardFooter>
          </form>
        </Form>
      </Card>
      
      {isLoading && (
        <div className="flex flex-col items-center justify-center rounded-lg border border-dashed p-12 gap-4">
            <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
            <p className="text-muted-foreground">Your contract is being generated by AI, please wait...</p>
        </div>
      )}

      {generatedContract && (
        <Card>
          <CardHeader>
            <CardTitle className="font-headline">Generated Contract Draft</CardTitle>
            <CardDescription>Review the generated contract below. You can copy it or request revisions.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="prose-sm max-w-none rounded-md border bg-muted/20 p-6 font-code">
              <pre className="whitespace-pre-wrap bg-transparent p-0 text-sm text-foreground">{generatedContract}</pre>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
